"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export const translations = {
  en: {
    // General
    coins: "Coins",
    login: "Login / Sign Up",
    joinCommunity: "Join the Community",
    joinDesc: "Create an account to add friends, join study rooms, and chat in real-time.",
    signUpFree: "Sign Up Free",
    marketplaceLocked: "Marketplace Locked",
    marketplaceLockedDesc: "Log in to earn coins during your focus sessions and buy exclusive study rooms!",
    addTask: "Add Task",
    notesPlaceholder: "Write your quick notes here... Markdown is supported.",
    ambientSounds: "Ambient Sounds",
    timerSettings: "Timer Settings",
    autoStartBreaks: "Auto-start Breaks",
    autoStartPomodoros: "Auto-start Pomodoros",
    notifications: "Notifications",
    soundAlarms: "Sound Alarms",
    buy: "Buy",
    equip: "Equip",
    free: "Free",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    
    // Timer
    focus: "Focus",
    break: "Break",
    session: "Session",
    startFocus: "Start",
    pauseTimer: "Pause",
    resetTimer: "Reset",
    completeTask: "Complete",
    // Widgets
    upNext: "Up Next",
    allCaughtUp: "All caught up!",
    widgetSettings: "Widget Settings",
    clockWeather: "Clock & Weather",
    statsLevel: "Level Stats",
    miniTasks: "Mini Tasks",
    musicPlayer: "Music Player",
    ambientMixer: "Ambient Mixer",
    // Settings
    focusLength: "Focus Length",
    breakLength: "Break Length",
    focusLengthDesc: "Focus time (Minutes)",
    breakLengthDesc: "Break time (Minutes)",
    automation: "Automation",
    displaySettings: "Display",
    // Tasks
    addTaskPlaceholder: "New task...",
    noTasks: "No tasks yet!",
    // Notes
    notes: "Notes",
    notesDesc: "Your quick notes (auto-saved)",
    // Music
    musicDesc: "Paste YouTube link or Video ID...",
    changeMusic: "Change",
    // Ambient
    rain: "Rain",
    cafe: "Cafe",
    fire: "Fireplace",
    keyboard: "Keyboard",
    ocean: "Ocean",
    // Profile
    editProfile: "Edit Profile",
    yourProfile: "Your Profile",
    newName: "New name",
    newPassword: "New password (leave blank to keep)",
    saveChanges: "Save",
    // Misc
    disableAllEffects: "Disable all effects",
    logout: "Logout",
    dailyMissions: "Daily Missions",
    missions: "Missions",
    missionCompleted: "Mission completed:",
    claimed: "Claimed",
    noMissionsToday: "No missions today",
    refreshAtMidnight: "Refreshes at midnight",
    paused: "Paused",
    nowPlaying: "Now Playing...",
    completed: "completed",
    allDone: "All done!",
    loading: "Loading...",
    level: "Level",
    xpProgress: "XP Progress",
    bronzeTier: "Bronze Tier",
    silverTier: "Silver Tier",
    goldTier: "Gold Tier",
    platinumTier: "Platinum Tier",
    diamondTier: "Diamond Tier",
    masterTier: "Master Tier",
    achievements: "Achievements",
    comingSoon: "Coming soon!",
    featureInDev: "This feature is currently in development.",
    analytics: "Analytics",
    totalStudyHours: "Total study hours",
    hours: "hours",
    completedSuffix: "completed",
    taskCompletionRate: "Task Completion Rate",
    tasksCompletedStatus: "You have completed {completed} out of {total} tasks created.",
    streak: "Streak",
    consecutiveDays: "consecutive days",
    settings: "Settings",
    member: "Member",
    
    stats: "Stats",
    music: "Music",
    addFriend: "Add Friend",
    friendsAlready: "Friends",
    sendMessage: "Message",
    mute: "Mute",
    kick: "Kick",
    ban: "Ban",
    dashboard: "Dashboard",
    friends: "Friends",
    chat: "Chat",
    room: "Room",
    
    
    recentActivity: "Recent Activity",
    noActivity: "No activity yet",
    startFocusDesc: "Start a focus session to earn coins!",
    marketplace: "Marketplace",
    tasks: "Tasks",
    cycle: "Cycle",
    sessionsPerRound: "Sessions per round",
    autoBreakDesc: "Auto switch to Break after Focus",
    autoFocusDesc: "Auto switch to Focus after Break",
    ringWhenDone: "Ring when time is up",
    weather: "Weather",
    city: "City",
    showWeather: "Show local weather",
    saveSettings: "Save Settings",
    marketplaceSubtitle: "Personalize your study space",
    roomTheme: "Room Theme",
    uploadedImage: "Uploaded Image",
    items: "items",
    noItemsFound: "No items found",
    markAllAsRead: "Mark all as read",
    noNotifications: "No notifications.",
    
    currentTier: "Current Tier",
    maxLevelReached: "Max Level Reached",
    totalPomodoros: "Total Pomodoros",
    currentStreak: "Current Streak",
    days: "days",
    pomodoroCompleted: "Pomodoro Completed",
    pomodoroFocusMessage: "You have focused for {sessions} sessions",
    taskCompleted: "Task Completed",
    taskCompletionMessage: "You have completed {tasks} tasks",
    xpToNextTier: "{pct}% to {nextTier}",
    
    bronzeMember: "Bronze Member",
    silverMember: "Silver Member",
    goldMember: "Gold Member",
    platinumMember: "Platinum Member",
    diamondMember: "Diamond Member",
    masterMember: "Master Member",
    
    
    
    
    
    
    maxTier: "Max Tier",

    leaveRoom: "Leave Room",
    personalSettings: "Personal Settings",
    youAreHost: "You are the Host",
    hostClockDesc: "Your clock is the standard reference time for everyone in the room.",
    syncPomodoro: "Sync Pomodoro",
    timeSyncsWithRoom: "Time syncs with room",

    todayWillDo: "Today I will do...",
    add: "Add",
    noTasksYet: "No tasks yet. Add a goal for today!",
    personalReport: "Personal Report",
    summaryCard: "Summary Card",
    
    syncPlayingForRoom: "Playing synced for room",
    nominateMusic: "Nominate Music",
    enterYoutubeId: "Enter YouTube Video ID...",
    
    nominate: "Nominate",
    voteList: "Vote List (Auto-change over 50%)",
    today: "Today",
    totalFocus: "Total Focus",
    leaderboard: "Leaderboard",






    categories: "CATEGORIES",
    all: "All",
    myImages: "My Images",
    lighting: "Lighting",
    sound: "Sound",
    pet: "Pet",
    effects: "Effects",
    cursor: "Cursor",
    badge: "Badge",
    searchItems: "Search items...",
    sortFeatured: "Featured",
    sortNewest: "Newest",
    sortPriceAsc: "Price: Low to High",
    sortPriceDesc: "Price: High to Low",
    dailyShop: "Daily Shop",
    dailyShopDesc: "Discounted items every day",
    viewNow: "View now →",
    uploadNewImage: "Upload New Image",
    uploadNewImageDesc: "Unlock the ability to upload your own background image",
    uploadImageBtn: "Upload Image",
    equippedStatus: "Equipped",
    unequip: "Unequip",

    // Toasts
    hostOnlyStartStop: "Only the host can start/stop the timer!",
    hostOnlyReset: "Only the host can reset the timer!",
    hostOnlySkip: "Only the host can skip the session!",
    hostOnlyChangeMode: "Only the host can change the mode!",
    roomCreated: "Room created successfully!",
    roomCreateError: "Error creating room, please try again!",
    systemError: "System error!",
    roomJoined: "Joined room!",
    roomJoinError: "Error joining room!",
    roomNotFound: "Room not found!",
    roomListError: "Error loading room list!",
    musicChanged: "🎵 Room music changed!",
    confirmSuccess: "✅ Confirmed successfully!",
    roomClosed: "Room closed or error occurred!",
    roomConnectError: "Room connection error!",
    syncOn: "Sync with room ON",
    syncOff: "Sync with room OFF",
    userKicked: "User kicked.",
    userKickError: "Could not kick user.",
    muteDev: "Mute feature is under development!",
    userBanned: "User banned from room!",
    friendRequestSent: "Friend request sent!",
    friendRequestError: "Could not send request.",
    loadMarketplaceError: "Could not load Marketplace",
    pleaseLogin: "Please log in!",
    purchaseFailed: "Purchase failed",
    purchaseSuccess: "Purchase successful",
    equipSuccess: "Equipped",
    petSpawned: "has spawned!",
    effectOn: "turned on",
    cursorChanged: "cursor changed",
    soundPlaying: "playing",
    badgeEquipped: "badge equipped",
    unequipAllSuccess: "All equipment & effects removed!",
    bgChangeSuccess: "Background changed successfully!",
    uploadFailed: "Upload failed.",
    uploadError: "Error uploading image.",
    min3Chars: "Enter at least 3 characters",
    sendFailed: "Send failed or already friends",
    friendAccepted: "Friend request accepted",
    deleted: "Deleted",
    updateSuccess: "Updated successfully!",
    updateError: "Error updating.",
    avatarUpdated: "Avatar updated!",
    avatarUpdateError: "Error uploading avatar.",
  },
  vi: {
    coins: "Xu",
    login: "Đăng nhập / Đăng ký",
    joinCommunity: "Tham gia Cộng đồng",
    joinDesc: "Tạo tài khoản để kết bạn, học nhóm và chat thời gian thực.",
    signUpFree: "Đăng ký Miễn phí",
    marketplaceLocked: "Cửa hàng đã khóa",
    marketplaceLockedDesc: "Đăng nhập để kiếm xu trong lúc học và mua các không gian xịn xò!",
    addTask: "Thêm công việc",
    notesPlaceholder: "Viết ghi chú nhanh ở đây... Hỗ trợ Markdown.",
    ambientSounds: "Âm thanh môi trường",
    timerSettings: "Cài đặt Đồng hồ",
    autoStartBreaks: "Tự động bắt đầu Nghỉ ngơi",
    autoStartPomodoros: "Tự động bắt đầu Học",
    notifications: "Thông báo",
    soundAlarms: "Âm thanh báo thức",
    buy: "Mua",
    equip: "Sử dụng",
    free: "Miễn phí",
    save: "Lưu",
    cancel: "Hủy",
    edit: "Chỉnh sửa",
    delete: "Xóa",
    
    focus: "Tập trung",
    break: "Nghỉ ngơi",
    session: "Phiên",
    startFocus: "Bắt đầu",
    pauseTimer: "Tạm dừng",
    resetTimer: "Đặt lại",
    completeTask: "Hoàn thành",
    upNext: "Tiếp theo",
    allCaughtUp: "Không có gì mới!",
    widgetSettings: "Cài đặt Widget",
    clockWeather: "Đồng hồ & Thời tiết",
    statsLevel: "Chỉ số cấp độ",
    miniTasks: "Nhiệm vụ nhỏ",
    musicPlayer: "Trình phát nhạc",
    ambientMixer: "Mix âm thanh",
    focusLength: "Thời gian Tập trung",
    breakLength: "Thời gian Nghỉ",
    focusLengthDesc: "Thời gian học (Phút)",
    breakLengthDesc: "Thời gian nghỉ (Phút)",
    automation: "Tự động hóa",
    displaySettings: "Hiển thị",
    addTaskPlaceholder: "Công việc mới...",
    noTasks: "Chưa có việc gì!",
    notes: "Ghi chú",
    notesDesc: "Ghi chú nhanh của bạn (tự lưu)",
    musicDesc: "Dán link YouTube hoặc Video ID vào đây...",
    changeMusic: "Đổi",
    rain: "Mưa",
    cafe: "Quán Café",
    fire: "Lửa trại",
    keyboard: "Bàn phím",
    ocean: "Sóng biển",
    editProfile: "Chỉnh sửa hồ sơ",
    yourProfile: "Hồ sơ của bạn",
    newName: "Tên mới",
    newPassword: "Mật khẩu mới (bỏ trống nếu không đổi)",
    saveChanges: "Lưu",
    disableAllEffects: "Tắt tất cả hiệu ứng",
    
    dailyMissions: "Nhiệm vụ hàng ngày",
    missions: "Nhiệm vụ",
    missionCompleted: "Hoàn thành:",
    claimed: "Đã nhận",
    noMissionsToday: "Chưa có nhiệm vụ nào",
    refreshAtMidnight: "Làm mới lúc 00:00",
    paused: "Đã tạm dừng",
    nowPlaying: "Đang phát...",
    completed: "hoàn thành",
    allDone: "Hoàn thành toàn bộ!",
    loading: "Đang tải...",
    level: "Cấp độ",
    xpProgress: "Tiến trình XP",
    bronzeTier: "Hạng Đồng",
    silverTier: "Hạng Bạc",
    goldTier: "Hạng Vàng",
    platinumTier: "Hạng Bạch Kim",
    diamondTier: "Hạng Kim Cương",
    masterTier: "Hạng Cao Thủ",
    achievements: "Thành tích",
    comingSoon: "Sắp ra mắt!",
    featureInDev: "Tính năng này đang được phát triển.",
    analytics: "Phân tích",
    totalStudyHours: "Tổng giờ học",
    hours: "giờ",
    completedSuffix: "hoàn thành",
    taskCompletionRate: "Tỷ lệ hoàn thành nhiệm vụ",
    tasksCompletedStatus: "Bạn đã hoàn thành {completed} trên tổng số {total} nhiệm vụ đã tạo.",
    streak: "Streak",
    consecutiveDays: "ngày liên tiếp",
    settings: "Cài đặt",
    member: "Thành viên",
    chat: "Chat",
    stats: "Thống kê",
    music: "Nhạc",
    addFriend: "Kết bạn",
    friendsAlready: "Đã kết bạn",
    sendMessage: "Nhắn tin",
    mute: "Tắt tiếng",
    kick: "Đuổi khỏi phòng",
    ban: "Cấm",
    dashboard: "Bảng điều khiển",
    friends: "Bạn bè",
    
    room: "Phòng học",
    
    totalPomodoros: "Tổng số phiên Pomodoro",
    recentActivity: "Hoạt động gần đây",
    noActivity: "Chưa có hoạt động nào",
    startFocusDesc: "Bắt đầu tập trung để kiếm xu!",
    marketplace: "Cửa hàng",
    tasks: "Nhiệm vụ",
    cycle: "Chu kỳ",
    sessionsPerRound: "Số phiên mỗi vòng",
    autoBreakDesc: "Tự nhảy sang Break khi xong Focus",
    autoFocusDesc: "Tự nhảy sang Focus khi xong Break",
    ringWhenDone: "Đổ chuông khi hết thời gian",
    weather: "Thời tiết",
    city: "Thành phố",
    showWeather: "Hiển thị thời tiết khu vực",
    saveSettings: "Lưu Cài Đặt",
    marketplaceSubtitle: "Cá nhân hóa không gian học tập của bạn",
    roomTheme: "Theme Phòng",
    uploadedImage: "Ảnh đã tải lên",
    items: "vật phẩm",
    noItemsFound: "Không tìm thấy vật phẩm nào",
    markAllAsRead: "Đã đọc tất cả",
    noNotifications: "Không có thông báo nào.",
    logout: "Đăng xuất",
    currentTier: "Hạng Hiện Tại",
    maxLevelReached: "Đã đạt cấp tối đa",
    
    currentStreak: "Chuỗi ngày",
    days: "ngày",
    pomodoroCompleted: "Hoàn thành Pomodoro",
    pomodoroFocusMessage: "Bạn đã tập trung được {sessions} phiên",
    taskCompleted: "Hoàn thành nhiệm vụ",
    taskCompletionMessage: "Bạn đã hoàn thành {tasks} nhiệm vụ",
    xpToNextTier: "{pct}% nữa lên {nextTier}",
    
    bronzeMember: "Thành viên Đồng",
    silverMember: "Thành viên Bạc",
    goldMember: "Thành viên Vàng",
    platinumMember: "Thành viên Bạch Kim",
    diamondMember: "Thành viên Kim Cương",
    masterMember: "Thành viên Bậc Thầy",
    
    
    
    
    
    
    maxTier: "Tối đa",

    leaveRoom: "Rời phòng",
    personalSettings: "Cài đặt cá nhân",
    youAreHost: "Bạn là Chủ phòng",
    hostClockDesc: "Đồng hồ của bạn là mốc thời gian chuẩn cho toàn bộ thành viên trong phòng.",
    syncPomodoro: "Đồng bộ Pomodoro",
    timeSyncsWithRoom: "Thời gian chạy theo phòng",

    todayWillDo: "Hôm nay tôi sẽ làm...",
    add: "Thêm",
    noTasksYet: "Chưa có nhiệm vụ nào. Hãy thêm mục tiêu cho hôm nay!",
    personalReport: "Báo cáo cá nhân",
    summaryCard: "Thẻ tổng kết",
    
    syncPlayingForRoom: "Phát đồng bộ cho cả phòng",
    nominateMusic: "Đề cử nhạc",
    enterYoutubeId: "Nhập YouTube Video ID...",
    
    nominate: "Đề cử",
    voteList: "Danh sách bình chọn (Quá 50% sẽ tự đổi)",
    today: "Hôm nay",
    totalFocus: "Tổng Focus",
    leaderboard: "Bảng xếp hạng",






    categories: "DANH MỤC",
    all: "Tất cả",
    myImages: "Ảnh của tôi",
    lighting: "Ánh sáng",
    sound: "Âm thanh",
    pet: "Pet",
    effects: "Hiệu ứng",
    cursor: "Con trỏ",
    badge: "Huy hiệu",
    searchItems: "Tìm kiếm vật phẩm...",
    sortFeatured: "Nổi bật",
    sortNewest: "Mới nhất",
    sortPriceAsc: "Giá thấp - cao",
    sortPriceDesc: "Giá cao - thấp",
    dailyShop: "Daily Shop",
    dailyShopDesc: "Vật phẩm giảm giá mỗi ngày",
    viewNow: "Xem ngay →",
    uploadNewImage: "Tải ảnh mới",
    uploadNewImageDesc: "Mở khóa tính năng tự tải ảnh nền từ thiết bị của bạn",
    uploadImageBtn: "Tải ảnh lên",
    equippedStatus: "Đang sử dụng",
    unequip: "Bỏ sử dụng",

    hostOnlyStartStop: "Chỉ chủ phòng mới có thể bắt đầu/dừng thời gian!",
    hostOnlyReset: "Chỉ chủ phòng mới có thể reset thời gian!",
    hostOnlySkip: "Chỉ chủ phòng mới có thể bỏ qua session!",
    hostOnlyChangeMode: "Chỉ chủ phòng mới có thể đổi chế độ!",
    roomCreated: "Phòng đã được tạo!",
    roomCreateError: "Lỗi tạo phòng, vui lòng thử lại!",
    systemError: "Lỗi hệ thống!",
    roomJoined: "Đã vào phòng!",
    roomJoinError: "Lỗi tham gia phòng!",
    roomNotFound: "Không tìm thấy phòng!",
    roomListError: "Lỗi tải danh sách phòng!",
    musicChanged: "🎵 Nhạc phòng đã được đổi!",
    confirmSuccess: "✅ Xác nhận thành công!",
    roomClosed: "Phòng đã bị đóng hoặc bị lỗi!",
    roomConnectError: "Lỗi kết nối phòng!",
    syncOn: "Đã BẬT đồng bộ với phòng",
    syncOff: "Đã TẮT đồng bộ với phòng",
    userKicked: "Đã đuổi người dùng.",
    userKickError: "Không thể đuổi người dùng.",
    muteDev: "Tính năng Mute đang được phát triển!",
    userBanned: "Đã cấm người dùng này vào phòng!",
    friendRequestSent: "Đã gửi lời mời kết bạn!",
    friendRequestError: "Không thể gửi lời mời.",
    loadMarketplaceError: "Không thể tải Marketplace",
    pleaseLogin: "Vui lòng đăng nhập!",
    purchaseFailed: "Mua thất bại",
    purchaseSuccess: "Mua thành công",
    equipSuccess: "Đã trang bị",
    petSpawned: "đã xuất hiện!",
    effectOn: "đã bật",
    cursorChanged: "đã đổi",
    soundPlaying: "đang phát",
    badgeEquipped: "đã trang bị",
    unequipAllSuccess: "Đã gỡ toàn bộ trang bị & hiệu ứng!",
    bgChangeSuccess: "Đã đổi hình nền thành công!",
    uploadFailed: "Tải lên thất bại.",
    uploadError: "Lỗi tải ảnh lên.",
    min3Chars: "Nhập ít nhất 3 ký tự",
    sendFailed: "Gửi thất bại hoặc đã là bạn bè",
    friendAccepted: "Đã chấp nhận kết bạn",
    deleted: "Đã xóa",
    updateSuccess: "Cập nhật thành công!",
    updateError: "Lỗi khi cập nhật.",
    avatarUpdated: "Đã cập nhật Avatar!",
    avatarUpdateError: "Lỗi khi upload avatar.",
  },
  zh: {
    coins: "硬币",
    login: "登录 / 注册",
    joinCommunity: "加入社区",
    joinDesc: "创建帐户以添加朋友，加入自习室并实时聊天。",
    signUpFree: "免费注册",
    marketplaceLocked: "市场已锁定",
    marketplaceLockedDesc: "登录以在专注期间赚取金币并购买专属自习室！",
    addTask: "添加任务",
    notesPlaceholder: "在这里写下您的快速笔记... 支持Markdown。",
    ambientSounds: "环境声音",
    timerSettings: "计时器设置",
    autoStartBreaks: "自动开始休息",
    autoStartPomodoros: "自动开始番茄钟",
    notifications: "通知",
    soundAlarms: "声音警报",
    buy: "购买",
    equip: "装备",
    free: "免费",
    save: "保存",
    cancel: "取消",
    edit: "编辑",
    delete: "删除",
    
    focus: "专注",
    break: "休息",
    session: "阶段",
    startFocus: "开始",
    pauseTimer: "暂停",
    resetTimer: "重置",
    completeTask: "完成",
    upNext: "接下来",
    allCaughtUp: "全部完成！",
    widgetSettings: "小组件设置",
    clockWeather: "时钟与天气",
    statsLevel: "等级状态",
    miniTasks: "小任务",
    musicPlayer: "音乐播放器",
    ambientMixer: "氛围混音器",
    focusLength: "专注时长",
    breakLength: "休息时长",
    focusLengthDesc: "专注时间（分钟）",
    breakLengthDesc: "休息时间（分钟）",
    automation: "自动化",
    displaySettings: "显示",
    addTaskPlaceholder: "新任务...",
    noTasks: "还没有任务！",
    notes: "笔记",
    notesDesc: "您的快速笔记（自动保存）",
    musicDesc: "粘贴YouTube链接或视频ID...",
    changeMusic: "更换",
    rain: "雨声",
    cafe: "咖啡馆",
    fire: "壁炉",
    keyboard: "键盘声",
    ocean: "海浪",
    editProfile: "编辑个人资料",
    yourProfile: "您的个人资料",
    newName: "新名字",
    newPassword: "新密码（不更改请留空）",
    saveChanges: "保存",
    disableAllEffects: "禁用所有效果",
    logout: "退出登录",
    dailyMissions: "每日任务",
    missions: "任务",
    missionCompleted: "任务完成:",
    claimed: "已领取",
    noMissionsToday: "今日无任务",
    refreshAtMidnight: "每日午夜刷新",
    paused: "已暂停",
    nowPlaying: "正在播放...",
    completed: "已完成",
    allDone: "全部完成！",
    loading: "加载中...",
    level: "等级",
    xpProgress: "经验进度",
    bronzeTier: "青铜级",
    silverTier: "白银级",
    goldTier: "黄金级",
    platinumTier: "铂金级",
    diamondTier: "钻石级",
    masterTier: "大师级",
    achievements: "成就",
    comingSoon: "即将推出！",
    featureInDev: "此功能目前正在开发中。",
    analytics: "分析",
    totalStudyHours: "总学习时间",
    hours: "小时",
    completedSuffix: "完成",
    taskCompletionRate: "任务完成率",
    tasksCompletedStatus: "您已完成总共 {total} 个任务中的 {completed} 个。",
    streak: "连续记录",
    consecutiveDays: "连续天数",
    settings: "设置",
    member: "成员",
    
    stats: "统计数据",
    music: "音乐",
    addFriend: "加好友",
    friendsAlready: "已是好友",
    sendMessage: "发送消息",
    mute: "静音",
    kick: "踢出房间",
    ban: "封禁",
    dashboard: "仪表板",
    friends: "朋友",
    chat: "聊天",
    room: "房间",
    
    
    recentActivity: "最近活动",
    noActivity: "暂无活动",
    startFocusDesc: "开始专注以赚取硬币！",
    marketplace: "市场",
    tasks: "任务",
    cycle: "周期",
    sessionsPerRound: "每轮阶段数",
    autoBreakDesc: "专注后自动切换到休息",
    autoFocusDesc: "休息后自动切换到专注",
    ringWhenDone: "时间到时响铃",
    weather: "天气",
    city: "城市",
    showWeather: "显示当地天气",
    saveSettings: "保存设置",
    marketplaceSubtitle: "个性化您的学习空间",
    roomTheme: "房间主题",
    uploadedImage: "已上传图片",
    items: "物品",
    noItemsFound: "未找到物品",
    markAllAsRead: "全部标为已读",
    noNotifications: "暂无通知。",
    
    currentTier: "当前等级",
    maxLevelReached: "已达最高等级",
    totalPomodoros: "番茄钟总数",
    currentStreak: "连续打卡",
    days: "天",
    pomodoroCompleted: "番茄钟完成",
    pomodoroFocusMessage: "您已专注了 {sessions} 个阶段",
    taskCompleted: "任务完成",
    taskCompletionMessage: "您已完成了 {tasks} 个任务",
    xpToNextTier: "距离 {nextTier} 还有 {pct}%",
    
    bronzeMember: "青铜会员",
    silverMember: "白银会员",
    goldMember: "黄金会员",
    platinumMember: "铂金会员",
    diamondMember: "钻石会员",
    masterMember: "大师会员",
    
    
    
    
    
    
    maxTier: "最高级别",

    leaveRoom: "离开房间",
    personalSettings: "个人设置",
    youAreHost: "您是房主",
    hostClockDesc: "您的时钟是房间内所有人的标准参考时间。",
    syncPomodoro: "同步番茄钟",
    timeSyncsWithRoom: "时间与房间同步",

    todayWillDo: "今天我将做...",
    add: "添加",
    noTasksYet: "暂无任务。为今天添加一个目标吧！",
    personalReport: "个人报告",
    summaryCard: "总结卡片",
    
    syncPlayingForRoom: "全房间同步播放",
    nominateMusic: "提名音乐",
    enterYoutubeId: "输入 YouTube 视频 ID...",
    
    nominate: "提名",
    voteList: "投票列表（超过 50% 将自动更换）",
    today: "今天",
    totalFocus: "总专注时间",
    leaderboard: "排行榜",






    categories: "分类",
    all: "全部",
    myImages: "我的图片",
    lighting: "灯光",
    sound: "声音",
    pet: "宠物",
    effects: "效果",
    cursor: "光标",
    badge: "徽章",
    searchItems: "搜索物品...",
    sortFeatured: "推荐",
    sortNewest: "最新",
    sortPriceAsc: "价格: 从低到高",
    sortPriceDesc: "价格: 从高到低",
    dailyShop: "每日商店",
    dailyShopDesc: "每天都有打折商品",
    viewNow: "立即查看 →",
    uploadNewImage: "上传新图片",
    uploadNewImageDesc: "解锁从设备上传自定义背景图片的功能",
    uploadImageBtn: "上传图片",
    equippedStatus: "已装备",
    unequip: "取消装备",

    hostOnlyStartStop: "只有房主可以开始/停止计时器！",
    hostOnlyReset: "只有房主可以重置计时器！",
    hostOnlySkip: "只有房主可以跳过当前阶段！",
    hostOnlyChangeMode: "只有房主可以更改模式！",
    roomCreated: "房间已创建！",
    roomCreateError: "创建房间出错，请重试！",
    systemError: "系统错误！",
    roomJoined: "已加入房间！",
    roomJoinError: "加入房间出错！",
    roomNotFound: "未找到房间！",
    roomListError: "加载房间列表出错！",
    musicChanged: "🎵 房间音乐已更改！",
    confirmSuccess: "✅ 确认成功！",
    roomClosed: "房间已关闭或发生错误！",
    roomConnectError: "房间连接错误！",
    syncOn: "与房间同步已开启",
    syncOff: "与房间同步已关闭",
    userKicked: "已踢出用户。",
    userKickError: "无法踢出用户。",
    muteDev: "静音功能正在开发中！",
    userBanned: "已将此用户从房间封禁！",
    friendRequestSent: "已发送好友请求！",
    friendRequestError: "无法发送请求。",
    loadMarketplaceError: "无法加载市场",
    pleaseLogin: "请登录！",
    purchaseFailed: "购买失败",
    purchaseSuccess: "购买成功",
    equipSuccess: "已装备",
    petSpawned: "已出现！",
    effectOn: "已开启",
    cursorChanged: "已更改游标",
    soundPlaying: "正在播放",
    badgeEquipped: "已装备徽章",
    unequipAllSuccess: "已卸下所有装备和效果！",
    bgChangeSuccess: "背景更换成功！",
    uploadFailed: "上传失败。",
    uploadError: "上传图片出错。",
    min3Chars: "请输入至少3个字符",
    sendFailed: "发送失败或已经是好友",
    friendAccepted: "已接受好友请求",
    deleted: "已删除",
    updateSuccess: "更新成功！",
    updateError: "更新出错。",
    avatarUpdated: "头像已更新！",
    avatarUpdateError: "上传头像出错。",
  }
};

export type Language = "en" | "vi" | "zh";
export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "vi",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>("vi");

  useEffect(() => {
    const saved = localStorage.getItem("promodo_lang") as Language;
    if (saved && ["en", "vi", "zh"].includes(saved)) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem("promodo_lang", newLang);
  };

  const t = (key: TranslationKey): string => {
    return translations[lang][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
